# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PoqApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoqApp
  pod 'Alamofire'
  pod 'EAAlert'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'

  target 'PoqAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoqAppUITests' do
    # Pods for testing
  end

end
